spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
spring.datasource.url=jdbc:derby://localhost:1527/melomandb;create=true
spring.datasource.username=lsea
spring.datasource.password=lsea

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=lsea
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE
