spring.application.name=project

# spring.datasource.url=jdbc:derby:melomandb;create=true

spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.DerbyDialect